### ISSUE TITLE
Usage of OCSPResponseBuilder

### ISSUE THREAD

**Issue by ghost** [wbond/ocspbuilder#10]
How will this class be used? I mean, as per my knowledge, server will make an OCSP request, query to the OCSP Server mentioned in the certificate. So Ideally OCSP Server should return the revocation status to our server. Why and how will we use the OCSPResponseBuilder to use the revocation status returned by OCSP Responder to our server?

**Comment by dbrgn** [comment]
This library ist just used to build the OCSP response (hence the name). It can be used to implement your own responder server.

Take a look at https://github.com/threema-ch/ocspresponder/ The code should work, but it hasn't been tested in production so far.

**Comment by ghost** [comment]
But what if I want the OCSP Server to respond with the revocation info, and not implement my own responder at all? Does OCSPRequestBuilder provide APIs to fetch the information from OCSP Server listed in the certificate?

**Comment by dbrgn** [comment]
You asked about the `OCSPResponseBuilder`, which is used to generate responses.

If you want to generate a request on the other hand, you need to send the request body to the responder URL via HTTP. Take a look at [Appendix A of RFC 6960](https://tools.ietf.org/html/rfc6960#appendix-A). You can use any HTTP client library for that.

**Comment by wbond** [comment]
https://github.com/wbond/certvalidator has a module `certvalidator.ocsp_client` that helps fetch OCSP information for a certificate. If you are working on trying to check a certificate and its revocation status, that library is probably what you want.

This library is primarily useful for building an OCSP response, but does provide a helper for generating the X.509 for a request also. The request generation isn't all that complicated, so certvalidator doesn't end up using ocspbuilder.

**Comment by wbond** [comment]
I should also note, for future reference, that the docs at https://github.com/wbond/ocspbuilder/blob/master/docs/readme.md provide basic usage examples.
