### ISSUE TITLE
Parsing requests

### ISSUE THREAD

**Issue by elad** [wbond/ocspbuilder#6]
Hello,

I'd like to implement my own OCSP server but there doesn't seem to be a way to parse requests. What am I missing?

**Comment by dbrgn** [comment]
Just as a sidenote, I already started such an attempt: https://github.com/threema-ch/ocspresponder

It's not used in production yet, but contributions and review are welcome :)

**Comment by dbrgn** [comment]
Oh, and by the way, a binary OCSP request in DER format can be parsed using `OCSPRequest.load(request_der)` (see https://github.com/threema-ch/ocspresponder/blob/b9486af68dd02b84e01bedabe4f6843a6ff0f698/ocspresponder/__init__.py#L133-L137)

**Comment by elad** [comment]
Hey @dbrgn, I cam across your project, but unfortunately Python 3 is a non-starter at the moment. Thanks for the pointer to asn1crypto.ocsp though! :)
